config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'urls#new'

  get  '' => 'urls#new'
  post '' => 'urls#create', as: 'url_create'

  get   ':token' => 'urls#show' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  include UrlValidator

  validates :token, :original_link, presence: true
  validates :token, uniqueness: true
  validates :original_link, uniqueness: { scope: :custom }
  validates :original_link, url: true
  validates :token, format: { with: /\A[a-zA-Z0-9\-\_]+\z/, message: 'only allows letters and numbers'}
  before_validation :generate_token, unless: :token?

private
  def generate_token
    token_len = 3
    3.times do |i|
      token = SecureRandom.urlsafe_base64 token_len+i
      if Url.find_by_token(token).blank?
        self.token = token
        break
      end
    end
    if self.token.blank?
      errors[:base] << "Out of token."
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)

    found_url = Url.find_by_original_link_and_custom(params[:url][:original_link], params[:url][:custom])

    if found_url.present?
      if params[:url][:custom] == 'true'
        flash[:alert] = "The link has already been shortened."
        render :new
      else
        redirect_to root_path, notice: "Your shorten url: #{root_url}#{found_url.token}"
      end
    else
      if @url.save
        redirect_to root_path, notice: "Your shorten url: #{root_url}#{@url.token}"
      else
        render :new
      end
    end
  end

  def show
    if params[:token].present?
      url = Url.find_by_token(params[:token])
      if url.present?
        redirect_to url.original_link
      else
        redirect_to root_path, alert: "Sorry, the url does not exist."
      end
    else
      redirect_to root_path
    end
  end

private
  def url_params
    params.require(:url).permit(:token, :original_link, :custom)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'success' then "alert alert-success fade in"
      when 'notice' then "alert alert-success fade in"
      when 'alert' then "alert alert-danger fade in"
      when 'error' then "alert alert-danger fade in"
      when 'warning' then "alert alert-warning fade in"
    end
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_errors.html.erb
<% target = local_assigns[:target] %>

<% if target.present? and target.errors.any? %>
  <div class="panel panel-danger error">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(target.errors.count, "error") %> need to be fixed:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% for message in target.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/urls/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-sm-12">
      <h1>LET'S SHORTEN YOUR LINK</h1>
      <h4>Make Your Link Easier to Remember</h4>
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <%= value %>
        </div>
      <% end %>
      <%= form_for @url, url: url_create_path, html: { role: "form" } do |f| %>
        <div class="row">
          <div class="form-group col-sm-12">
            <%= render partial: 'partials/errors', locals: { target: @url } %>
          </div>
          <div class="form-group col-sm-6">
            <%= f.url_field :original_link, class: 'form-control', placeholder: 'Put your destination URL here. ex: http://google.com', required: true %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-1">
            <%= f.select :custom, options_for_select([["Default", 'false'], ["Custom", "true"]], selected: f.object.custom), {class: 'form-control', required: true } %>
          </div>
          <div class="form-group col-sm-5">
            <%= f.text_field :token, class: "form-control #{f.object.custom ? '' : 'hidden'}", placeholder: 'Put your shorten ex: MyMusic' %>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-sm-6">
            <%= f.submit "Create", class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>